/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tv_aroundme_incrementalupdate_BsPatch */

#ifndef _Included_tv_aroundme_incrementalupdate_BsPatch
#define _Included_tv_aroundme_incrementalupdate_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tv_aroundme_incrementalupdate_BsPatch
 * Method:    bsPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tv_aroundme_incrementalupdate_BsPatch_bsPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
