/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class tv_aroundme_update_BsDiff */

#ifndef _Included_tv_aroundme_update_BsDiff
#define _Included_tv_aroundme_update_BsDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tv_aroundme_update_BsDiff
 * Method:    bsDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tv_aroundme_update_BsDiff_bsDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
